### ISSUE TITLE
Wrong reduced VAT rate for CZ?

### ISSUE THREAD

**Issue by mtarnovan** [ibericode/vat-rates#19]
According to [this article](https://amavat.eu/changes-in-vat-czech-republic-coming-into-effect-from-1-january-2024/#:~:text=VAT%20rates%20in%20the%20Czech,%3A%20remains%20unchanged%20at%2021%25.) reduced VAT rates of 10% and 15% were consolidated into a single reduced VAT rate of 12% starting from 2024-01-01. Currently the JSON file still contains the older VAT rates.

**Comment by dannyvankooten** [comment]
Nicely spotted @mtarnovan - I was able to confirm your findings and added the new consolidated reduced rate in d5eaabaf37e3259f0e8533e3eb7a69e407aab68b. Thank you for contributing!
