### ISSUE TITLE
German VAT "DE" is still 19%

### ISSUE THREAD

**Issue by targor** [ibericode/vat-rates#5]
the vat in germany changed until the end of the year to 16%

**Comment by Mark-H** [comment]
[It's correct in the source file](https://github.com/ibericode/vat-rates/blob/master/vat-rates.json#L417-L421); make sure the client you use to read the data uses the right value based on the `effective_date`.

**Comment by dannyvankooten** [comment]
Yes, what @Mark-H says. Please don’t telt on ordening as future rates may already have been announced and in the array. 

I’ll take a look at making that more clear in the documentation.

**Comment by targor** [comment]
ah, thank you for the hint.. did not look closely enough..
