### ISSUE TITLE
vat-rates.json is not a valid JSON file

### ISSUE THREAD

**Issue by akosphp** [ibericode/vat-rates#7]
A comma is missing in line 126.

Error: Parse error on line 126:
...g": 13.5				}			} {				"effective_fro
---------------------^
Expecting 'EOF', '}', ',', ']', got '{'

**Comment by dannyvankooten** [comment]
fixed in 4a604a74dbf2305c51982035f3d28782260f942b, thank you @akosphp !

**Comment by Mark-H** [comment]
Whoops, my bad 😬
